version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: betteruptime_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - betteruptime_data:/var/lib/postgresql/data

volumes:
  betteruptime_data:
